export type AssessmentControlDef = {
  code: string;
  category: string;
  title: string;
  severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
  questionCodes: string[];
  findingTypes: string[];
  docKeywords: string[];
};

/** Deterministic DPDP control library used by the assessment engine. */
export const ASSESSMENT_CONTROL_REGISTRY: AssessmentControlDef[] = [
  {
    code: "DPDP-CONSENT-NOTICE",
    category: "Consent",
    title: "Privacy notice present and meaningful",
    severity: "HIGH",
    questionCodes: ["Q-NOTICE-PUBLISHED"],
    findingTypes: ["notice_language", "consent_reference"],
    docKeywords: ["privacy notice", "collect", "personal data"],
  },
  {
    code: "DPDP-CONSENT-COLLECT",
    category: "Consent",
    title: "Consent collected before processing",
    severity: "HIGH",
    questionCodes: ["Q-CONSENT-COLLECT"],
    findingTypes: ["consent_reference"],
    docKeywords: ["consent"],
  },
  {
    code: "DPDP-CONSENT-WITHDRAW",
    category: "Consent",
    title: "Consent withdrawal available",
    severity: "HIGH",
    questionCodes: ["Q-CONSENT-WITHDRAW"],
    findingTypes: ["consent_withdrawal"],
    docKeywords: ["withdraw", "withdrawal"],
  },
  {
    code: "DPDP-RIGHTS-ACCESS",
    category: "Rights",
    title: "Access request handling",
    severity: "HIGH",
    questionCodes: ["Q-RIGHTS-ACCESS"],
    findingTypes: ["access_endpoint"],
    docKeywords: ["access request", "right to access"],
  },
  {
    code: "DPDP-RIGHTS-CORRECT",
    category: "Rights",
    title: "Correction request handling",
    severity: "HIGH",
    questionCodes: ["Q-RIGHTS-CORRECT"],
    findingTypes: ["access_endpoint"],
    docKeywords: ["correction", "rectification", "update personal"],
  },
  {
    code: "DPDP-RIGHTS-ERASURE",
    category: "Rights",
    title: "Erasure / deletion request handling",
    severity: "CRITICAL",
    questionCodes: ["Q-RIGHTS-DELETE"],
    findingTypes: ["deletion_endpoint", "erasure_logic"],
    docKeywords: ["erasure", "delete", "right to be forgotten"],
  },
  {
    code: "DPDP-RIGHTS-GRIEVANCE",
    category: "Rights",
    title: "Grievance redressal workflow",
    severity: "HIGH",
    questionCodes: ["Q-GRIEVANCE"],
    findingTypes: ["grievance_reference"],
    docKeywords: ["grievance"],
  },
  {
    code: "DPDP-BREACH-DETECT",
    category: "Breach",
    title: "Breach detection capability",
    severity: "CRITICAL",
    questionCodes: ["Q-BREACH-PROCESS"],
    findingTypes: ["breach_reference"],
    docKeywords: ["breach", "incident"],
  },
  {
    code: "DPDP-BREACH-NOTIFY",
    category: "Breach",
    title: "Breach notification workflow",
    severity: "CRITICAL",
    questionCodes: ["Q-BREACH-PROCESS"],
    findingTypes: ["breach_reference"],
    docKeywords: ["notify", "board", "72"],
  },
  {
    code: "DPDP-RETENTION-SCHEDULE",
    category: "Retention",
    title: "Retention schedule exists",
    severity: "MEDIUM",
    questionCodes: ["Q-RETENTION"],
    findingTypes: ["retention_reference", "retention_config"],
    docKeywords: ["retention"],
  },
  {
    code: "DPDP-RETENTION-LOGS",
    category: "Retention",
    title: "Log retention configured",
    severity: "MEDIUM",
    questionCodes: ["Q-RETENTION"],
    findingTypes: ["retention_config", "retention_reference"],
    docKeywords: ["log retention", "retention"],
  },
  {
    code: "DPDP-VENDOR-INVENTORY",
    category: "Vendors",
    title: "Vendor / processor inventory",
    severity: "HIGH",
    questionCodes: ["Q-VENDORS", "Q-VENDOR-INVENTORY"],
    findingTypes: ["vendor_reference"],
    docKeywords: ["vendor", "processor", "subprocessor"],
  },
  {
    code: "DPDP-VENDOR-DPA",
    category: "Vendors",
    title: "Data processing agreements in place",
    severity: "HIGH",
    questionCodes: ["Q-DPA"],
    findingTypes: ["vendor_reference"],
    docKeywords: ["dpa", "data processing agreement"],
  },
  {
    code: "DPDP-GOV-OWNER",
    category: "Governance",
    title: "Privacy owner assigned",
    severity: "MEDIUM",
    questionCodes: ["Q-PRIVACY-OWNER"],
    findingTypes: [],
    docKeywords: ["privacy officer", "dpo", "data protection"],
  },
  {
    code: "DPDP-GOV-TRAINING",
    category: "Governance",
    title: "Privacy training program",
    severity: "LOW",
    questionCodes: ["Q-TRAINING"],
    findingTypes: [],
    docKeywords: ["training"],
  },
  {
    code: "DPDP-SDF-DPO",
    category: "SDF",
    title: "DPO assigned when SDF applicable",
    severity: "HIGH",
    questionCodes: ["Q-SDF", "Q-DPO"],
    findingTypes: [],
    docKeywords: ["data protection officer", "dpo"],
  },
  {
    code: "DPDP-CONSENT-MGR",
    category: "Consent",
    title: "Consent Manager readiness",
    severity: "HIGH",
    questionCodes: ["Q-CONSENT-MGR"],
    findingTypes: ["consent_manager"],
    docKeywords: ["consent manager", "intermediary"],
  },
  {
    code: "DPDP-GRIEVANCE-OFFICER",
    category: "Rights",
    title: "Grievance officer appointed and published",
    severity: "HIGH",
    questionCodes: ["Q-GRIEVANCE-OFFICER"],
    findingTypes: ["grievance_officer"],
    docKeywords: ["grievance officer", "grievance redressal"],
  },
  {
    code: "DPDP-AUTO-DELETE",
    category: "Retention",
    title: "Automated erasure on purpose expiry",
    severity: "HIGH",
    questionCodes: ["Q-AUTO-DELETE"],
    findingTypes: ["auto_delete", "retention_config"],
    docKeywords: ["automated deletion", "auto delete", "purpose expiry", "48 hour"],
  },
];
