import type { QuestionnaireQuestion } from "./questionnaire-types.js";

/**
 * Universal DPDP operational questions shown for every organisation.
 * Industry packs append on top via getQuestionnaireCatalogForDomain().
 */
export const CORE_QUESTIONNAIRE: QuestionnaireQuestion[] = [
  {
    code: "Q-AUDIT-NOTICE-PUBLIC",
    stageId: "engineering_audit",
    stageLabel: "Engineering audit",
    stageOrder: 0,
    label:
      "Is a privacy notice published on public surfaces (website/app) stating why data is collected?",
    helpText:
      "Engineering audit — auditor’s eyes on public claims, not only an uploaded PDF.",
    valueType: "boolean",
    required: true,
  },
  {
    code: "Q-AUDIT-CONTACT-CHANNEL",
    stageId: "engineering_audit",
    stageLabel: "Engineering audit",
    stageOrder: 0,
    label:
      "Is a clear contact / grievance channel published for data principal rights requests?",
    helpText: "Visitors must know where to ask for access, correction, or erasure.",
    valueType: "boolean",
    required: true,
  },
  {
    code: "Q-AUDIT-HOSTING-REGION",
    stageId: "engineering_audit",
    stageLabel: "Engineering audit",
    stageOrder: 0,
    label: "Where is primary personal data hosted?",
    helpText: "Maps India vs overseas hosting for transfer and localisation risk.",
    valueType: "string",
    options: ["INDIA_ONLY", "MULTI_REGION", "OUTSIDE_INDIA", "UNKNOWN"],
    required: true,
  },
  {
    code: "Q-AUDIT-INFORMAL-CHANNELS",
    stageId: "engineering_audit",
    stageLabel: "Engineering audit",
    stageOrder: 0,
    label:
      "Is personal data shared via informal channels (WhatsApp, personal email, unmanaged sheets)?",
    helpText:
      "Informal channels are a common engineering-audit finding and raise processor/access risk.",
    valueType: "boolean",
    required: true,
  },
  {
    code: "Q-AUDIT-SYSTEMS-MAPPED",
    stageId: "engineering_audit",
    stageLabel: "Engineering audit",
    stageOrder: 0,
    label:
      "Have you mapped internal systems that store personal data (CRM, apps, DBs, vendors)?",
    helpText:
      "System discovery is the first step before Trace-like continuous controls.",
    valueType: "boolean",
    required: true,
  },
  {
    code: "Q-BIZ-MODEL",
    stageId: "org_profile",
    stageLabel: "Organisation profile",
    stageOrder: 1,
    label: "Who do you primarily process personal data for?",
    helpText:
      "B2C means individuals (customers/users). B2B means other organisations. This shapes notice, consent and rights expectations under DPDP.",
    valueType: "string",
    options: ["B2C", "B2B", "BOTH"],
    required: true,
  },
  {
    code: "Q-DATA-VOLUME",
    stageId: "org_profile",
    stageLabel: "Organisation profile",
    stageOrder: 1,
    label: "Approximate scale of digital personal data you process",
    helpText:
      "Used for SDF readiness signalling (volume is one factor the Act contemplates for Significant Data Fiduciaries).",
    valueType: "string",
    options: ["UNDER_10K", "10K_TO_100K", "100K_TO_1M", "OVER_1M"],
    required: true,
  },
  {
    code: "Q-DATA-CATEGORIES",
    stageId: "org_profile",
    stageLabel: "Organisation profile",
    stageOrder: 1,
    label: "What is the primary high-risk personal data category you process?",
    helpText:
      "Pick the dominant sensitive category. Contact-only is lowest sensitivity; health, biometric, children and government ID raise safeguards.",
    valueType: "string",
    options: [
      "CONTACT",
      "FINANCIAL",
      "HEALTH",
      "BIOMETRIC",
      "LOCATION",
      "CHILDREN",
      "GOVERNMENT_ID",
      "BEHAVIOURAL",
      "OTHER",
    ],
    required: true,
  },
  {
    code: "Q-CHILDREN-DATA",
    stageId: "org_profile",
    stageLabel: "Organisation profile",
    stageOrder: 1,
    label: "Do you knowingly process personal data of children (under 18)?",
    helpText:
      "Children’s data attracts stricter verifiable-consent and restriction duties under DPDP Section 9.",
    valueType: "boolean",
    required: true,
  },
  {
    code: "Q-CROSS-BORDER",
    stageId: "org_profile",
    stageLabel: "Organisation profile",
    stageOrder: 1,
    label: "Is personal data transferred or accessible outside India?",
    helpText:
      "Cross-border access affects transfer approvals and contractual safeguards with processors.",
    valueType: "boolean",
    required: true,
  },
  {
    code: "Q-FIDUCIARY-ROLE",
    stageId: "org_profile",
    stageLabel: "Organisation profile",
    stageOrder: 1,
    label:
      "For most processing, are you the Data Fiduciary (decide purpose/means) or mainly a Processor?",
    helpText:
      "Fiduciaries own notice, consent and rights duties. Processors follow customer instructions under a contract.",
    valueType: "string",
    options: ["FIDUCIARY", "PROCESSOR", "MIXED"],
    required: true,
  },
  {
    code: "Q-NOTICE-PUBLISHED",
    stageId: "notice_consent",
    stageLabel: "Notice & consent",
    stageOrder: 3,
    label: "Do you publish a privacy notice before collecting personal data?",
    helpText:
      "Upload your live privacy notice under Documents (type: Privacy notice). DPDP requires clear notice of purpose and rights.",
    valueType: "boolean",
    required: true,
  },
  {
    code: "Q-NOTICE-PURPOSE",
    stageId: "notice_consent",
    stageLabel: "Notice & consent",
    stageOrder: 3,
    label:
      "Does the notice state purposes in clear, itemised language (not only buried T&Cs)?",
    helpText:
      "Purpose limitation fails when processing purposes are vague or bundled into terms of service.",
    valueType: "boolean",
    required: true,
  },
  {
    code: "Q-CONSENT-COLLECT",
    stageId: "notice_consent",
    stageLabel: "Notice & consent",
    stageOrder: 3,
    label: "Where consent is the basis, is it collected before processing starts?",
    helpText:
      "Consent must be free, specific, informed, unconditional and clear. Prefer purpose-linked consent records over bundled T&Cs.",
    valueType: "boolean",
    required: true,
  },
  {
    code: "Q-CONSENT-WITHDRAW",
    stageId: "notice_consent",
    stageLabel: "Notice & consent",
    stageOrder: 3,
    label: "Can a Data Principal withdraw consent as easily as they gave it?",
    helpText:
      "Withdrawal must be as easy as giving consent. Upload consent procedures and ensure CLI can find a withdraw endpoint/workflow.",
    valueType: "boolean",
    required: true,
  },
  {
    code: "Q-CONSENT-MANAGER",
    stageId: "notice_consent",
    stageLabel: "Notice & consent",
    stageOrder: 3,
    label: "Do you use (or plan to use) a registered Consent Manager?",
    helpText:
      "Consent Managers are optional but help portable, interoperable consent under the DPDP Rules.",
    valueType: "boolean",
    required: true,
  },
  {
    code: "Q-RIGHTS-ACCESS",
    stageId: "rights",
    stageLabel: "Data Principal rights",
    stageOrder: 4,
    label: "Can individuals request access to their personal data?",
    helpText:
      "Access requests need a tracked channel and response process. Upload your rights SOP if you have one.",
    valueType: "boolean",
    required: true,
  },
  {
    code: "Q-RIGHTS-CORRECT",
    stageId: "rights",
    stageLabel: "Data Principal rights",
    stageOrder: 4,
    label: "Can individuals request correction of inaccurate personal data?",
    helpText: "Correction is a core Data Principal right under DPDP.",
    valueType: "boolean",
    required: true,
  },
  {
    code: "Q-RIGHTS-DELETE",
    stageId: "rights",
    stageLabel: "Data Principal rights",
    stageOrder: 4,
    label: "Can individuals request erasure of their personal data?",
    helpText:
      "Erasure (with lawful exceptions) should be operational, not email-only. CLI looks for deletion/erasure endpoints as technical evidence.",
    valueType: "boolean",
    required: true,
  },
  {
    code: "Q-RIGHTS-NOMINATION",
    stageId: "rights",
    stageLabel: "Data Principal rights",
    stageOrder: 4,
    label: "Do you support nomination / nominee rights where applicable?",
    helpText:
      "DPDP provides for nomination in certain circumstances — have an operational path even if rarely used.",
    valueType: "boolean",
    required: true,
  },
  {
    code: "Q-GRIEVANCE",
    stageId: "rights",
    stageLabel: "Data Principal rights",
    stageOrder: 4,
    label: "Is a grievance redressal contact / process published?",
    helpText:
      "DPDP requires a readily available means to raise grievances, with timelines for response.",
    valueType: "boolean",
    required: true,
  },
  {
    code: "Q-GRIEVANCE-SLA",
    stageId: "rights",
    stageLabel: "Data Principal rights",
    stageOrder: 4,
    label: "Do you respond to grievances within 90 days (Rules timeline)?",
    helpText:
      "The DPDP Rules set a 90-day grievance redressal timeline — track SLA from receipt to closure.",
    valueType: "boolean",
    required: true,
  },
  {
    code: "Q-VENDORS",
    stageId: "vendors",
    stageLabel: "Vendors & processors",
    stageOrder: 5,
    label: "Do you use vendors or other processors for personal data?",
    helpText:
      "Data Fiduciaries remain accountable for processors. If yes, you will be asked about DPAs.",
    valueType: "boolean",
    required: true,
  },
  {
    code: "Q-DPA",
    stageId: "vendors",
    stageLabel: "Vendors & processors",
    stageOrder: 5,
    label: "Do signed data processing agreements cover those processors?",
    helpText:
      "Upload sample DPAs under Documents (type: Vendor / processor DPA).",
    valueType: "boolean",
    required: true,
    showIf: { code: "Q-VENDORS", equals: true },
  },
  {
    code: "Q-VENDOR-INVENTORY",
    stageId: "vendors",
    stageLabel: "Vendors & processors",
    stageOrder: 5,
    label: "Do you maintain an inventory of processors and their purposes?",
    helpText:
      "An inventory (name, purpose, location, DPA status) is the operational backbone of vendor accountability.",
    valueType: "boolean",
    required: true,
    showIf: { code: "Q-VENDORS", equals: true },
  },
  {
    code: "Q-RETENTION",
    stageId: "retention_breach",
    stageLabel: "Retention & breach readiness",
    stageOrder: 6,
    label: "Is a retention schedule defined for personal data (and logs)?",
    helpText:
      "Upload your retention schedule. CLI also looks for retention settings in code/config.",
    valueType: "boolean",
    required: true,
  },
  {
    code: "Q-RETENTION-ERASURE",
    stageId: "retention_breach",
    stageLabel: "Retention & breach readiness",
    stageOrder: 6,
    label:
      "Is there an automated or operational erasure when purpose ends / retention expires?",
    helpText:
      "A schedule without deletion workflows leaves data after purpose fulfilment — a common DPDP gap.",
    valueType: "boolean",
    required: true,
  },
  {
    code: "Q-BREACH-PROCESS",
    stageId: "retention_breach",
    stageLabel: "Retention & breach readiness",
    stageOrder: 6,
    label: "Do you have a documented personal-data breach response process?",
    helpText:
      "Cover detection, internal escalation, Board notification path, and affected-principal communication. Upload the incident/breach policy.",
    valueType: "boolean",
    required: true,
  },
  {
    code: "Q-BREACH-NOTIFY",
    stageId: "retention_breach",
    stageLabel: "Retention & breach readiness",
    stageOrder: 6,
    label:
      "Does the process include notifying the Board and affected principals as required?",
    helpText:
      "Breach duties include Data Protection Board notification within 72 hours and informing affected Data Principals.",
    valueType: "boolean",
    required: true,
  },
  {
    code: "Q-GRIEVANCE-OFFICER",
    stageId: "rights",
    stageLabel: "Data Principal rights",
    stageOrder: 4,
    label: "Is a grievance officer appointed with published name and contact details?",
    helpText:
      "DPDP s.8(6) mandates a grievance officer — distinct from a general grievance process contact.",
    valueType: "boolean",
    required: true,
  },
  {
    code: "Q-CONSENT-MGR",
    stageId: "notice_consent",
    stageLabel: "Notice & consent",
    stageOrder: 2,
    label: "Are you prepared to integrate with registered Consent Managers per DPDP Rule 4?",
    helpText:
      "Consent Managers are registered intermediaries — assess readiness before the November 2026 registration deadline.",
    valueType: "boolean",
    required: true,
  },
  {
    code: "Q-AUTO-DELETE",
    stageId: "retention_breach",
    stageLabel: "Retention & breach readiness",
    stageOrder: 6,
    label:
      "When purpose expires, is data automatically erased with 48-hour advance notice to data principals?",
    helpText:
      "DPDP Rule 8 mandates automated erasure when purpose is no longer served, with 48-hour advance notice.",
    valueType: "boolean",
    required: true,
  },
  {
    code: "Q-LOG-RETENTION",
    stageId: "retention_breach",
    stageLabel: "Retention & breach readiness",
    stageOrder: 6,
    label:
      "Are security / processing logs retained as required for oversight (Rules: ~1 year where applicable)?",
    helpText:
      "Log retention supports investigation and regulatory oversight without indefinite personal-data hoarding.",
    valueType: "boolean",
    required: true,
  },
  {
    code: "Q-PRIVACY-OWNER",
    stageId: "governance",
    stageLabel: "Governance",
    stageOrder: 7,
    label: "Is a named privacy / compliance owner accountable for DPDP?",
    helpText:
      "Accountability needs a human owner even if you are not an SDF.",
    valueType: "boolean",
    required: true,
  },
  {
    code: "Q-TRAINING",
    stageId: "governance",
    stageLabel: "Governance",
    stageOrder: 7,
    label: "Do staff who handle personal data receive privacy training?",
    helpText: "Training reduces operational breach and rights-handling failures.",
    valueType: "boolean",
    required: true,
  },
  {
    code: "Q-SDF",
    stageId: "governance",
    stageLabel: "Governance",
    stageOrder: 7,
    label: "Are you (or likely to be classified as) a Significant Data Fiduciary?",
    helpText:
      "SDFs face extra duties (DPO, audits, DPIA). Answer based on volume, sensitivity and risk — not a legal determination.",
    valueType: "boolean",
    required: true,
  },
  {
    code: "Q-DPO",
    stageId: "governance",
    stageLabel: "Governance",
    stageOrder: 7,
    label: "Have you appointed a Data Protection Officer?",
    helpText: "Required for SDFs; strongly recommended otherwise if scale is high.",
    valueType: "boolean",
    required: true,
    showIf: { code: "Q-SDF", equals: true },
  },
  {
    code: "Q-DPIA",
    stageId: "governance",
    stageLabel: "Governance",
    stageOrder: 7,
    label:
      "Do you conduct data protection impact / risk assessments for high-risk processing?",
    helpText: "SDF-oriented duty; also good practice for high-risk categories.",
    valueType: "boolean",
    required: true,
    showIf: { code: "Q-SDF", equals: true },
  },
  {
    code: "Q-AUDIT",
    stageId: "governance",
    stageLabel: "Governance",
    stageOrder: 7,
    label: "Have you had an independent or internal privacy audit in the last 12 months?",
    helpText: "Audits evidence ongoing accountability for SDFs and mature programmes.",
    valueType: "boolean",
    required: true,
    showIf: { code: "Q-SDF", equals: true },
  },

  // --- Security safeguards (also exported in Excel workbook) -----------------
  {
    code: "Q-SEC-PHYSICAL",
    stageId: "security_safeguards",
    stageLabel: "Security safeguards",
    stageOrder: 8,
    label:
      "Describe physical security controls for premises / data centres that store personal data",
    helpText:
      "Access badges, CCTV, visitor logs, locked server rooms, co-lo provider controls, etc.",
    valueType: "string",
    required: true,
  },
  {
    code: "Q-SEC-ENCRYPT-REST",
    stageId: "security_safeguards",
    stageLabel: "Security safeguards",
    stageOrder: 8,
    label: "Is personal data encrypted at rest in primary storage systems?",
    helpText: "Disk / volume / application-level encryption for databases and object stores.",
    valueType: "boolean",
    required: true,
  },
  {
    code: "Q-SEC-ENCRYPT-DB",
    stageId: "security_safeguards",
    stageLabel: "Security safeguards",
    stageOrder: 8,
    label:
      "Describe how databases encrypt personal data (algorithm, TDE/column, managed service)",
    helpText:
      "e.g. AES-256 TDE on Postgres RDS, column encryption for PAN, Mongo field-level encryption.",
    valueType: "string",
    required: true,
  },
  {
    code: "Q-SEC-KEY-MGMT",
    stageId: "security_safeguards",
    stageLabel: "Security safeguards",
    stageOrder: 8,
    label: "How are encryption keys managed and rotated?",
    helpText: "KMS/HSM, customer-managed keys, rotation cadence, access to key material.",
    valueType: "string",
    required: true,
  },
  {
    code: "Q-SEC-ENCRYPT-TRANSIT",
    stageId: "security_safeguards",
    stageLabel: "Security safeguards",
    stageOrder: 8,
    label: "Is personal data encrypted in transit (TLS) for apps, APIs and admin access?",
    helpText: "TLS 1.2+ for public and internal APIs, VPN/SSH for admin paths.",
    valueType: "boolean",
    required: true,
  },
];
