/**
 * Frozen permission catalog — resource:action strings.
 * All modules must use these exact strings. Add new permissions here before using them.
 */
export const PERMISSIONS = {
  // organizations
  ORGANIZATION_CREATE: "organization:create",
  ORGANIZATION_READ: "organization:read",
  ORGANIZATION_UPDATE: "organization:update",

  // users
  USER_CREATE: "user:create",
  USER_READ: "user:read",
  USER_UPDATE: "user:update",
  USER_INVITE: "user:invite",

  // roles
  ROLE_CREATE: "role:create",
  ROLE_READ: "role:read",
  ROLE_UPDATE_PERMISSIONS: "role:update_permissions",
  ROLE_ASSIGN: "role:assign",

  // departments
  DEPARTMENT_CREATE: "department:create",
  DEPARTMENT_READ: "department:read",
  DEPARTMENT_UPDATE: "department:update",

  // framework / controls / requirements
  FRAMEWORK_GENERATE: "framework:generate",
  FRAMEWORK_READ: "framework:read",
  FRAMEWORK_PUBLISH: "framework:publish",
  CONTROL_CREATE: "control:create",
  CONTROL_READ: "control:read",
  CONTROL_UPDATE: "control:update",
  REQUIREMENT_CREATE: "requirement:create",
  REQUIREMENT_READ: "requirement:read",

  // inventory (Dev B)
  DATA_ASSET_CREATE: "data_asset:create",
  DATA_ASSET_READ: "data_asset:read",
  DATA_ASSET_UPDATE: "data_asset:update",
  DATA_ASSET_DELETE: "data_asset:delete",
  PROCESSING_ACTIVITY_CREATE: "processing_activity:create",
  PROCESSING_ACTIVITY_READ: "processing_activity:read",
  PROCESSING_ACTIVITY_UPDATE: "processing_activity:update",
  PROCESSING_ACTIVITY_DELETE: "processing_activity:delete",

  // consent (Dev B)
  NOTICE_READ: "notice:read",
  CONSENT_CREATE: "consent:create",
  CONSENT_WITHDRAW: "consent:withdraw",

  // rights (Dev B)
  RIGHTS_REQUEST_CREATE: "rights_request:create",
  RIGHTS_REQUEST_READ: "rights_request:read",
  RIGHTS_REQUEST_UPDATE: "rights_request:update",

  // validations / violations / remediation (Dev B)
  VALIDATION_RUN: "validation:run",
  VALIDATION_READ: "validation:read",
  VIOLATION_READ: "violation:read",
  VIOLATION_ASSIGN: "violation:assign",
  VIOLATION_CLOSE: "violation:close",
  REMEDIATION_READ: "remediation:read",
  REMEDIATION_UPDATE: "remediation:update",

  // evidence / reports / analytics (Dev C)
  EVIDENCE_CREATE: "evidence:create",
  EVIDENCE_READ: "evidence:read",
  EVIDENCE_APPROVE: "evidence:approve",
  EVIDENCE_EXPORT: "evidence:export",
  REPORT_GENERATE: "report:generate",
  REPORT_READ: "report:read",
  ANALYTICS_READ: "analytics:read",

  // notifications / ai / audit (Dev C)
  NOTIFICATION_READ: "notification:read",
  NOTIFICATION_PREFERENCES_UPDATE: "notification:update_preferences",
  AI_EXPLAIN: "ai:explain",
  AI_DRAFT: "ai:draft",
  AUDIT_READ: "audit:read",
  AUDIT_EXPORT: "audit:export",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ALL_PERMISSIONS: Permission[] = Object.values(PERMISSIONS);

/** System role permission presets seeded at org creation. */
export const SYSTEM_ROLE_PRESETS: Record<string, Permission[]> = {
  ORG_ADMIN: ALL_PERMISSIONS,
  DPO: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_INVITE,
    PERMISSIONS.ROLE_READ,
    PERMISSIONS.DEPARTMENT_READ,
    PERMISSIONS.FRAMEWORK_GENERATE,
    PERMISSIONS.FRAMEWORK_READ,
    PERMISSIONS.FRAMEWORK_PUBLISH,
    PERMISSIONS.CONTROL_CREATE,
    PERMISSIONS.CONTROL_READ,
    PERMISSIONS.CONTROL_UPDATE,
    PERMISSIONS.REQUIREMENT_CREATE,
    PERMISSIONS.REQUIREMENT_READ,
    PERMISSIONS.DATA_ASSET_READ,
    PERMISSIONS.PROCESSING_ACTIVITY_READ,
    PERMISSIONS.NOTICE_READ,
    PERMISSIONS.CONSENT_CREATE,
    PERMISSIONS.CONSENT_WITHDRAW,
    PERMISSIONS.RIGHTS_REQUEST_CREATE,
    PERMISSIONS.RIGHTS_REQUEST_READ,
    PERMISSIONS.RIGHTS_REQUEST_UPDATE,
    PERMISSIONS.VALIDATION_RUN,
    PERMISSIONS.VALIDATION_READ,
    PERMISSIONS.VIOLATION_READ,
    PERMISSIONS.VIOLATION_ASSIGN,
    PERMISSIONS.VIOLATION_CLOSE,
    PERMISSIONS.REMEDIATION_READ,
    PERMISSIONS.REMEDIATION_UPDATE,
    PERMISSIONS.EVIDENCE_CREATE,
    PERMISSIONS.EVIDENCE_READ,
    PERMISSIONS.EVIDENCE_APPROVE,
    PERMISSIONS.EVIDENCE_EXPORT,
    PERMISSIONS.REPORT_GENERATE,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.AI_EXPLAIN,
    PERMISSIONS.AI_DRAFT,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.AUDIT_EXPORT,
  ],
  COMPLIANCE_OFFICER: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.USER_READ,
    PERMISSIONS.DEPARTMENT_READ,
    PERMISSIONS.FRAMEWORK_READ,
    PERMISSIONS.CONTROL_READ,
    PERMISSIONS.REQUIREMENT_READ,
    PERMISSIONS.DATA_ASSET_CREATE,
    PERMISSIONS.DATA_ASSET_READ,
    PERMISSIONS.PROCESSING_ACTIVITY_CREATE,
    PERMISSIONS.PROCESSING_ACTIVITY_READ,
    PERMISSIONS.NOTICE_READ,
    PERMISSIONS.CONSENT_CREATE,
    PERMISSIONS.RIGHTS_REQUEST_READ,
    PERMISSIONS.RIGHTS_REQUEST_UPDATE,
    PERMISSIONS.VALIDATION_RUN,
    PERMISSIONS.VALIDATION_READ,
    PERMISSIONS.VIOLATION_READ,
    PERMISSIONS.VIOLATION_ASSIGN,
    PERMISSIONS.REMEDIATION_READ,
    PERMISSIONS.REMEDIATION_UPDATE,
    PERMISSIONS.EVIDENCE_CREATE,
    PERMISSIONS.EVIDENCE_READ,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.AI_EXPLAIN,
  ],
  AUDITOR: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.USER_READ,
    PERMISSIONS.ROLE_READ,
    PERMISSIONS.DEPARTMENT_READ,
    PERMISSIONS.FRAMEWORK_READ,
    PERMISSIONS.CONTROL_READ,
    PERMISSIONS.REQUIREMENT_READ,
    PERMISSIONS.DATA_ASSET_READ,
    PERMISSIONS.PROCESSING_ACTIVITY_READ,
    PERMISSIONS.NOTICE_READ,
    PERMISSIONS.RIGHTS_REQUEST_READ,
    PERMISSIONS.VALIDATION_READ,
    PERMISSIONS.VIOLATION_READ,
    PERMISSIONS.REMEDIATION_READ,
    PERMISSIONS.EVIDENCE_READ,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.AUDIT_EXPORT,
  ],
  MEMBER: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.DEPARTMENT_READ,
    PERMISSIONS.FRAMEWORK_READ,
    PERMISSIONS.CONTROL_READ,
    PERMISSIONS.DATA_ASSET_READ,
    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.NOTIFICATION_PREFERENCES_UPDATE,
  ],
};
