-- AlterEnum
ALTER TYPE "RuleCategory" ADD VALUE IF NOT EXISTS 'SECURITY';
ALTER TYPE "RuleCategory" ADD VALUE IF NOT EXISTS 'BREACH';
ALTER TYPE "RuleCategory" ADD VALUE IF NOT EXISTS 'TRANSFER';
ALTER TYPE "RuleCategory" ADD VALUE IF NOT EXISTS 'CHILDREN';
ALTER TYPE "RuleCategory" ADD VALUE IF NOT EXISTS 'GOVERNANCE';
ALTER TYPE "RuleCategory" ADD VALUE IF NOT EXISTS 'PURPOSE';
