name: CI

on:
  push:
    branches: [main, develop, "feature/**"]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: dpdpos
          POSTGRES_PASSWORD: dpdpos
          POSTGRES_DB: dpdpos
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U dpdpos -d dpdpos"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 10
    env:
      DATABASE_URL: postgresql://dpdpos:dpdpos@localhost:5432/dpdpos?schema=public
      REDIS_URL: redis://localhost:6379
      JWT_ACCESS_SECRET: ci-access-secret-change-me-32chars!!
      JWT_REFRESH_SECRET: ci-refresh-secret-change-me-32chars!
      S3_ENDPOINT: http://localhost:9000
      S3_REGION: us-east-1
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
      S3_BUCKET: dpdpos-evidence
      S3_FORCE_PATH_STYLE: "true"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: npm
      - run: npm ci
      - run: npx prisma generate
      - run: npx prisma migrate deploy
      - run: npm run prisma:seed
      - run: npm run lint
      - run: npm run build
      - run: npm test
 
